#!/bin/bash

## highlights words  in certain colors

# Accumulate the REGEX expression
ARGS="(^"
for ARG in "$@"
do
	if [ "$1" = "--color" ]
	then
		shift
		case $1 in

			gre*|GRE*)
				GREP_COLOR="1;32"
				;;
			red|RED)
				GREP_COLOR="1;31"
				;;
			yel*|YEL*)
				GREP_COLOR="1;33"
				;;
			blu*|BLU*)
				GREP_COLOR="1;34"
				;;
			*)
				;;
		esac
	else
		ARGS=$ARGS"|$1"
	fi

	shift
done
ARGS=$ARGS")"

GREP_COLOR=$GREP_COLOR grep --color=always -E "(^|$ARGS)"
